### ISSUE TITLE
network structure

### ISSUE THREAD

**Issue by huangzehao** [xuw080/towards-universal-objects-detection#5]
Hi, xudong @xuw080 ,
I have some questions about the network structure of universal detector.
Are there multiple detection head in the universal detector? For example, for Faster-RCNN with ResNet50, the final stage of ResNet50 (C5) followed by a classification fc layer and a bbox regression fc layer is adopted as the detection head. 
I show the sturcture as following:
shared backbone feature->C5_1->bbox fc_1 + cls fc_1->KITTI Result
shared backbone feature->C5_2->bbox fc_2 + cls fc_2->VOC Result
shared backbone feature->C5_3->bbox fc_3 + cls fc_3->COCO Result
Am I right?

**Comment by frank-xwang** [comment]
Yes, it is correct. Sorry for the late reply.
